version: "3.8"
services:
    mysql:
        image: mysql:8.0
        container_name: mysql_local
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 666666
            MYSQL_DATABASE: book
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    redis:
        image: redis:7
        container_name: redis_local
        ports:
            - "6379:6379"
