spring:
    datasource:
        url: jdbc:mysql://localhost:3306/book
        username: root
        password: 666666
        driver-class-name: com.mysql.cj.jdbc.Driver
    data:
        redis:
            host: localhost
            port: 6379
            database: 0

mybatis:
    mapper-locations: classpath:angelowu/mapper/*.xml
    type-aliases-package: angelowu.pojo
    configuration:
        map-underscore-to-camel-case: true
